# 9조 신재우, OOO, OOO

---
# Numpy Array와 Python List의 비교

## 1. array & numpy.argmin()

In [16]:
import numpy as np

ar1 = np.array([1, 2, 3, 4])  # [1, 2, 3, 4]
ar2 = np.arange(4, 0, -1)     # [4, 3, 2, 1]

result = np.argmin(ar1)
print(result)

result = np.argmin(ar2)
print(result)

0
3


위 코드 결과와 같이 `argmin()` 함수는 array에서 가장 작은 값의 인덱스를 반환합니다. 

## 2. 실행 시간 비교 (%timeit)

발표 편의를 위해 실행 시간을 먼저 비교하겠습니다.

numpy의 argmin() 함수와 직접 만든 함수의 작동 시간을 비교합니다. 

우선 임의의 2차원 배열과 리스트를 다음과 같이 만들었습니다. 

10 * 5 행렬과 같은 모양입니다. 

In [11]:
import random as r
python_list = [[r.randrange(1, 10) for i in range(5)] for j in range(10)]
numpy_array = np.array(list1)
print(python_list)
print(numpy_array)

[[4, 4, 4, 6, 8], [6, 3, 9, 2, 9], [2, 5, 8, 2, 5], [4, 1, 9, 1, 9], [4, 7, 5, 7, 6], [2, 4, 4, 4, 1], [9, 4, 8, 4, 3], [4, 8, 9, 1, 4], [3, 3, 6, 7, 6], [4, 2, 4, 3, 3]]
[[5 2 4 6 2]
 [2 4 1 9 4]
 [8 4 9 2 2]
 [6 7 1 2 8]
 [8 2 9 6 8]
 [2 1 9 6 2]
 [7 8 7 7 9]
 [8 9 9 7 3]
 [7 4 5 8 9]
 [4 3 8 7 2]]


<br>

먼저 `axis=0`일 때의 작동 시간 비교입니다. 입력값이 많을 경우 numpy의 argmin 함수가 더 빠른 것을 볼 수 있습니다. 

In [12]:
%timeit np.argmin(array1, axis=0)

1.59 µs ± 5.32 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [13]:
%timeit argmin(list1, axis=0)

5.02 µs ± 157 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


<br>

`axis=1`일 때의 작동 시간 비교입니다. 마찬가지로 numpy의 함수가 더 빠르게 동작합니다. 

In [14]:
%timeit np.argmin(array1, axis=1)

1.18 µs ± 3.53 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [15]:
%timeit argmin(list1, axis=1)

3.02 µs ± 14.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## 3. Python list & 직접 작성한 argmin()

### (1) Numpy Array

2차원의 ndarray를 만들고, `argmin()` 함수에 axis 값을 바꿔가며 계산하면 다음과 같습니다. 

In [10]:
array = np.array([[5, 6, 8], [5, 7, 1], [2, 8, 4]])
result1 = np.argmin(array, axis=0)
result2 = np.argmin(array, axis=1)
print(array, '\n')
print(result1)
print(result2)

[[5 6 8]
 [5 7 1]
 [2 8 4]] 

[2 0 1]
[0 2 0]


2차원 array는 `axis=0`일 때 `array`에 속한 각각의 1차원 리스트를 행 방향(↓)으로 비교해서, 

즉 `[5, 5, 2], [6, 7, 8], [8, 1, 4]`의 각 리스트의 최솟값의 인덱스인 `[2, 0, 1]`을 반환합니다. 

`axis=1`일 때는 `array`에 속한 각각의 1차원 리스트 `[5, 6, 8], [5, 7, 1], [2, 8, 4]`의 최솟값의 인덱스인 `[0, 2, 0]`을 반환합니다.

<br> 

### (2) Python List

#### 핵심 코드

```python
# code
리스트.index(min(리스트))

# example
>>> list1 = [1, 2, 3]
>>> list1.index(min(list1))    
0    # 최솟값 1의 인덱스인 0를 반환합니다.
```

위 코드가 함수의 핵심입니다. 리스트 최솟값의 인덱스를 반환합니다. 

numpy 라이브러리를 이용하지 않고 python에서 numpy의 `argmin()`와 동일한 함수를 만들면 다음과 같습니다. <br>
<br>
입력값이 2차원 리스트임을 전제로 작성한 함수이므로 2차원 리스트를 입력할 때만 정상적으로 작동합니다.<br>
<br>
또한 axis를 입력하는 방법을 구체화하지 않았고 axis에 0이 입력되는 경우, 1이 입력되는 경우로만 분기했으며 입력값이 잘못된 예외에 대해서는 크게 신경쓰지 않았습니다.<br>
<br>

In [3]:
def argmin(array, axis):
    col = len(array[0])
    result_array = []
    if axis == 0:
        for i in range(col):
            temp = []
            for a in array:
                temp.append(a[i])
            result_array.append(temp.index(min(temp)))
        return result_array
    elif axis == 1:
        for a in array:
            result_array.append(a.index(min(a)))
        return result_array
    else:
        return "error"

In [ ]:
def argmin2(a, axis):
    result=[]   #결과를 담을 배열
    min=0   #작은 요소를 담을 변수(여기에 각 요소마다 비교하여 가장 최솟값을 저장함)
    b=0   #최솟값의 행이나 열 정보(인덱스)를 담을 변수  
    
    if axis==0 or axis==-2:   #axis=0인 경우(행을 남기고 열을 없앰)
        for i in range(len(a[0])):   #한 열의 길이를 대상으로 실행
            min=a[0][i]   #일단 각 열의 첫번째 요소를 min으로 정한다.
            for j in range(len(a)):   #같은 열 내에서 첫 번째 요소보다 작은 값이 있을 경우 그 값을 min으로 업데이트
                if min>a[j][i]:
                    min=a[j][i]
                    b=j   #한 열에 대해서 for문이 다 돌고 난 최종값(min) 요소의 행 인덱스가 우리가 필요한 정보
            result.append(b)   #바로 윗 줄에서 나온 정보를 함수의 맨 처음에 선언한 빈 배열(result[])에 차례대로 저장
                
                
    if axis==1 or axis==-1:  #axis=1인 경우 (열을 남기고 행을 없앰)
        for row in range(len(a)):   #한 행의 길이 대상으로 실행
            min=a[row][0]   #각 행의 첫 번째 dythfmf min으로 정한다
            for column in range(len(a[row])):   #같은 행 내에서 첫 번째 요소보다 작은 값이 있을 경우 그 값을 min으로 없데이트
                if min>a[row][column]:
                    min=a[row][column]
                    b=column   #한 행에 대해서 for문이 다 돌고 난 최종값(min)의 요소의 열 인덱스가 우리가 필요한 정보
            result.append(b)   #바로 윗 줄에서 나온 정보를 함수의 맨 처음에 선언한 빈 배열(result[])에 차례대로 저장
            
    return(result) #result배열 반환

In [4]:
array = [[5, 6, 8], [5, 7, 1], [2, 8, 4]]
result1 = argmin(array, axis=0)
result2 = argmin(array, axis=1)
print(result1)
print(result2)

[2, 0, 1]
[0, 2, 0]


np.argmin()에서 사용한 예시와 같은 입력값에서 같은 결과가 출력되면서 잘 작동합니다. 



<br>

#### 함수

함수를 위에서부터 차례대로 살펴보겠습니다. 
<br><br>

```python
def argmin(array, axis):
    col = len(array[0])
    result_array = []
```


함수를 사용할 때 배열과 axis를 입력받습니다. 

그리고 2차원 리스트를 행렬처럼 생각할 때 열에 해당하는 축의 길이를 첫번째 원소(행)의 길이(열)를 이용해 미리 입력했습니다. 

예를 들어 위에서 작성했던 `[[5, 6, 8], [5, 7, 1], [2, 8, 4]]` 리스트를 입력값으로 하는 함수의 `col` 값은 3이 됩니다. 

이는 뒤에서 반복문 사용을 편리하게 하기 위함입니다. 

<br>

```python
if axis == 0:
    for i in range(col):
        temp = []
        for a in array:
            temp.append(a[i])
        result_array.append(temp.index(min(temp)))
    return result_array
```


axis가 0인 경우, 각 행의 같은 인덱스를 가진 값들을 비교합니다. 

모든 행을 순회하며 같은 인덱스의 값을 임시 리스트 `temp`에 모은 뒤, `temp`의 최소값의 인덱스를 결과 리스트에 저장합니다.

해당 명령을 열의 개수만큼 반복하면 원하는 결과를 얻을 수 있습니다. 

<br>

```python
elif axis == 1:
    for a in array:
        result_array.append(a.index(min(a)))
    return result_array
```


axis가 1인 경우, 모든 행을 순회하며 각 행의 최솟값의 인덱스를 결과 리스트에 저장하여 반환합니다. 

<br>

```python
else:
    return "error"
```


axis에 0이나 1이 아닌 값을 입력할 경우 오류 메시지를 반환합니다. 
<br><br>