# 신재우 2015123056 / 최원주, 이다솜

---
# Numpy Array와 Python List의 비교

## np.argmax

In [1]:
import numpy as np

ar1 = np.array([1, 2, 3, 4])  # [1, 2, 3, 4]
ar2 = np.arange(4, 0, -1)     # [4, 3, 2, 1]

result = np.argmax(ar1)
print(result)

result = np.argmax(ar2)
print(result)

3
0


위 코드 결과와 같이 `argmax()` 함수는 array에서 가장 큰 값의 인덱스를 반환합니다. 

## (1) Numpy Array

2차원의 ndarray를 만들고, `argmax()` 함수에 axis 값을 바꿔가며 계산하면 다음과 같습니다. 

In [2]:
array = np.array([[5, 6, 8], [5, 7, 1], [2, 8, 4]])
result2 = np.argmax(array, axis=0)
result3 = np.argmax(array, axis=1)
print(result2)
print(result3)

[0 2 0]
[2 1 1]


2차원 array는 `axis=0`일 때 행 방향으로 같은 인덱스의 값끼리 비교합니다. <br>
즉, 각각의 행 `[5, 5, 2], [6, 7, 8], [8, 1, 4]`에서 최대값의 인덱스인 `[0, 2, 0]`을 반환합니다. <br>
`axis=1`일 때는 `[5, 6, 8], [5, 7, 1], [2, 8, 4]`에서 열 방향으로 비교해서, `[2, 1, 1]`을 반환합니다.
<br> <br>

## (2) Python List

numpy 라이브러리를 이용하지 않고 python에서 numpy의 `argmax()`와 동일한 함수를 만들면 다음과 같습니다. <br>
<br>
입력값이 2차원 리스트임을 전제로 작성한 함수이므로 2차원 리스트를 입력할 때만 정상적으로 작동합니다.<br>
<br>
또한 axis를 입력하는 방법을 구체화하지 않았고 axis에 0이 입력되는 경우, 1이 입력되는 경우로만 분기했으며 입력값이 잘못된 예외에 대해서는 크게 신경쓰지 않았습니다.<br>
<br>

In [3]:
def argmax(array, axis):
    col = len(array[0])
    result_array = []
    if axis == 0:
        for i in range(col):
            temp = []
            for a in array:
                temp.append(a[i])
            result_array.append(temp.index(max(temp)))
        return result_array
    elif axis == 1:
        for a in array:
            result_array.append(a.index(max(a)))
        return result_array
    else:
        return "error"

In [4]:
array = [[5, 6, 8], [5, 7, 1], [2, 8, 4]]
result2 = argmax(array, axis=0)
result3 = argmax(array, axis=1)
print(result2)
print(result3)

[0, 2, 0]
[2, 1, 1]


```python
# code
리스트.index(max(리스트))

# example
>>> list1 = [1, 2, 3]
>>> list1.index(max(list1))    
2    # 최대값 3의 인덱스인 2를 반환합니다.
```

위 코드가 함수의 핵심입니다. 리스트 최댓값의 인덱스를 반환합니다. 
<br><br>
함수를 위에서부터 차례대로 살펴보겠습니다. 
<br><br>

```python
def argmax(array, axis):
    col = len(array[0])
    result_array = []
```

<br>
함수를 사용할 때 배열과 axis를 입력받습니다. <br>
그리고 2차원 리스트를 행렬처럼 생각할 때 열에 해당하는 축의 길이를 첫번째 원소(행)의 길이(열)를 이용해 미리 입력했습니다. <br>
예를 들어 위에서 작성했던 `array` 리스트를 입력값으로 하는 함수의 `col` 값은 3이 됩니다. <br>
이는 뒤에서 반복문 사용을 편리하게 하기 위함입니다. <br>
<br>

```python
if axis == 0:
    for i in range(col):
        temp = []
        for a in array:
            temp.append(a[i])
        result_array.append(temp.index(max(temp)))
    return result_array
```

<br>
axis가 0인 경우, 각 행의 같은 인덱스를 가진 값들을 비교하며 계산합니다. <br>
모든 행을 순회하며 같은 인덱스의 값을 임시 리스트 temp에 모은 뒤, temp의 최대값의 인덱스를 결과 리스트에 저장합니다. <br>
해당 명령을 열의 개수만큼 반복하면 우리가 원하는 결과를 얻을 수 있습니다. <br>
<br>

```python
elif axis == 1:
    for a in array:
        result_array.append(a.index(max(a)))
    return result_array
```

<br>
axis가 1인 경우, 모든 행을 순회하며 각 행의 최대값의 인덱스를 결과 리스트에 저장하여 반환합니다. <br>
<br>

```python
else:
    return "error"
```

<br>
axis에 0이나 1이 아닌 값을 입력할 경우 오류 메시지를 반환합니다. <br>
<br>

## 실행 시간 비교 (%timeit)

 numpy의 함수와 직접 만든 함수의 작동 시간을 비교합니다. 

우선 임의의 2차원 배열과 리스트를 다음과 같이 만들었습니다. 

In [5]:
import random as r
list1 = [[r.randrange(1, 10) for i in range(4)] for j in range(r.randrange(2, 6))]
array1 = np.array(list1)
print(list1)
print(array1)

[[5, 7, 5, 8], [6, 8, 3, 8], [7, 7, 7, 2], [8, 6, 6, 7]]
[[5 7 5 8]
 [6 8 3 8]
 [7 7 7 2]
 [8 6 6 7]]


<br>
먼저 `axis=0`일 때의 작동 시간 비교입니다. 

In [6]:
%timeit argmax(list1, axis=0)

10.6 µs ± 1.72 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
%timeit np.argmax(array1, axis=0)

6.32 µs ± 343 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


<br>
`axis=1`일 때의 작동 시간 비교입니다.

In [8]:
%timeit argmax(list1, axis=1)

5.07 µs ± 862 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
%timeit np.argmax(array1, axis=1)

4.09 µs ± 292 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
